### ISSUE TITLE
Response data when error

### ISSUE THREAD

**Issue by egbulmer** [tkf/emacs-request#16]
I am experimenting with `request` by making queries to CouchDB:

``` lisp
(request-response-data
 (request
  "http://127.0.0.1:5984/albums"
  :type "PUT"
  :parser 'json-read
  :sync 'yes))
```

This will respond with `((ok . t))` the first time and then `nil` afterwards because the database already exists. CouchDB raises a 412 error but also returns some JSON:

``` js
{
  "error" : "file_exists",
  "reason" : "The database could not be created, the file already exists."
}
```

Do you know if I can access this error data with `request`?

**Comment by ardumont** [comment]
@abingham Regarding melpa, it's not that much of a deal. 
it's simply a matter of changing the repository's url recipe.
But i think, it would need discussion with @tkf first, if he could.

**Comment by abingham** [comment]
Right, there are no real technical challenges to any of this. But we need @tkf to participate, but he doesn't seem to be paying attention.

**Comment by marsam** [comment]
Giving that there is not response from @tkf. I was thinking, should we promote a fork and change the melpa recipe?

**Comment by ardumont** [comment]
> Giving that there is not response from @tkf. 

I've tried to contact him via twitter - https://twitter.com/aka_tkf...
So now we can wait for a response...

> I was thinking, should we promote a fork and change the melpa recipe?

Well, I'm not particularly pleased to bypass that way but it could be one way...

It could be a good idea to ask to melpa fellows (@purcell is one of them) if this already happened.
(I'm pretty sure it did with the package nrepl which became cider... but i don't know the details...)

Cheers,

**Comment by abingham** [comment]
I've [asked @purcell about this before](https://github.com/milkypostman/melpa/issues/1994), and his view was that @tkf was probably too busy to bother with us, so we would have to deal with it somehow.

**Comment by purcell** [comment]
That was a long time ago, so if one of you wants to commit to maintaining a fork, then just agree it among yourselves and send us a PR to update the recipe.

**Comment by ardumont** [comment]
@purcell thanks for the help :D 

Also, note that there are 2 packages involved: `request` and `request-deferred`.

And there are at least 2 other packages system (i just thought of checking this morning...):

- marmalade: https://marmalade-repo.org/packages/request 
(with https://github.com/nicferrier/emacs-marmalade-upload, it's just a matter to call this after a release on request.el and request-deferred.el buffers and automate on this is feasible)

- el-get: https://github.com/dimitri/el-get/blob/411feeb4b584c451bf2b88f49d2f6f835283c441/recipes/request.rcp (just a PR to adapt the recipe like melpa...)

This would mean migrating those 2 (maybe not immediately).
Otherwise, it could make users befuddled in the long run...

@dimitri @nicferrier sorry to bother you about this, do you have a `the main package maintainer does not respond anymore in any way, stuck are we. Can we switch other to a fork?` policy?

Cheers,

**Comment by dimitri** [comment]
No policy for that, but the main policy for el-get recipe is that if you are a user, it doesn't work and you know how to fix it, please do. that includes using forks.

**Comment by ardumont** [comment]
@dimitri Thanks!

--

Just referencing some other investigation.
There are tests but you need tornado and flask (python2 here, api servers) as o.s. dependencies to make them pass. As for emacs' test dependencies, it's cask/cask.
(I have no idea about the coverage though.)

For debian-based people, packages are python-tornado and python-flask.

Cheers,

**Comment by titaniumbones** [comment]
@dimitri @ardumont @nicferrier is this still an issue for you & do you have fixes? I am working on merging features that others implement, but I am not competent to address these kinds of larger issues myself. Thank you!

**Comment by dickmao** [comment]
Statute of limitations on issues is roughly five years.
