### ISSUE TITLE
Is it support response contains utf-8 characters ? 

### ISSUE THREAD

**Issue by oaksharks** [tkf/emacs-request#88]
I have received the response with some chinese characters , but they are shown as numbers like 
```json
 {"weatherinfo":{"city":"\345\214\227\344\272\254"}}
```
Is there any suggestions ?

**Comment by davidshepherd7** [comment]
Hi, I just ran into this problem and the solution was to encode the string as 'utf-8 after doing the json encode (and I guess you would do something similar for decoding if you need to decode).

Here's the patch for my use-case: https://github.com/davidshepherd7/anki-mode/commit/e052de184fb8eff9d382fb0d0dbb267777662f7f (I also switched to using a threading macro in the same commit, I hope it's still clear what the change was).

I got the idea from syohex's response to [this issue](https://github.com/myuhe/org-gcal.el/issues/48), so that might be helpful too.

**Comment by oaksharks** [comment]
@davidshepherd7 Thanks for your reply . Just as your said I try to encode the response string:
```lisp
(encode-coding-string response-json-data 'utf-8)
```
but it does not works then I tried the decode function:
 ```lisp
(decode-coding-string response-json-data 'utf-8)
```
I just got the right result .
but I do not understand why the name of this function is `decode-coding-string` .

**Comment by davidshepherd7** [comment]
I'm not really sure, but I think it's because it "decodes" a string which is coded in some non-emacs-native system (e.g. utf8) into emacs' native system.

**Comment by oaksharks** [comment]
I got that ,  it's already encoded in `uft-8` but  emacs just can not recognize that , so decode data by using `utf-8` to bytes(or other thing)  .  Thanks again .
