### ISSUE TITLE
Data alists not parsed to JSON recursively?

### ISSUE THREAD

**Issue by titaniumbones** [tkf/emacs-request#94]
I don't know if anyone's listening and I'm not sure if this is my problem or request's, but it seems to me that request is not able to handle more comple data structures when passed to `data`, e.g. this one:
```emacs-lisp
`("column_data" . ,(((column_id . 721) (user_id . 100120) (content)) ((column_id . 723) (user_id . 100120) (content . is)) ((column_id . 721) (user_id . 2937) (content)) ((column_id . 723) (user_id . 2937) (content . hi)) ((column_id . 721) (user_id . 11696) (content)) ((column_id . 723) (user_id . 11696) (content . this)) ((column_id . 721) (user_id . 33649) (content)) ((column_id . 723) (user_id . 33649) (content . is)) ((column_id . 721) (user_id . 140846) (content)) ((column_id . 723) (user_id . 140846) (content . it))))
```
From what I cna tell, the data is not being encoded properly to JSON, or anyway I am getting a 400 response from the server. Do other people see the same thing?

**Comment by titaniumbones** [comment]
Ah man, I realized all I have to do is set ad `("Content-type" . "applicaion/json")` to `:headers` and set  `:data (json-encode data)` manually before.  I would love to see some more extensive docuentation here! @tkf would you be ope nto a PR?

**Comment by dangom** [comment]
Did you try validating the json structure somewhere else to see if it's valid?

Maybe save it to a .json file and try `python -m json.tool "$file"`. Or just copy paste it in https://jsonlint.com/, if the content is not sensitive.

But more likely then not, the json will be valid. 

The issue is probably not with json.el or request.el, but your API endpoint expecting a different format.
I've had problems with 400 responses because of nested structures, but the problem was not because of the json,which was valid, but because the endpoint expected a string `"foo"` and not a list `("foo")`.

There's also a similar issue here: #74

**Comment by titaniumbones** [comment]
Closing as invalid, this was user error!
